### PR TITLE
Setup Linting

### PR DESCRIPTION
**Pull request by FatBoyXPC**

### CODE REVIEW

**Comment by david-fairbanks42** [comment]
Probably my OCD coming through...
Not a fan of the trailing comma `'trailing_comma_in_multiline_array' => true`
I also like to line up my arrows in multi-line arrays but I don't see a rule for that.
I'll have to get used to adding spaces after `if`.
Other than that, I like it.

**Comment by FatBoyXPC** [comment]
I actually have the multi-line array arrows and even regular assignment (`=`) to be 1 space around each, so that they _won't_ line up. Awhile ago I used to agree so hard on aligning all the things, but then a friend pointed out how you sometimes have to re-align things and it makes the git diff harder to understand. I still disagreed with that up until I had a larger diff and had to determine _why_ the whole thing was shifted and once I saw it was the alignment I was like "Oh...dang it...he was right." So that's the same spirit behind always having a trailing comma in multi line arrays. I'd do it for function signatures, too, if PHP supported it.

It's worth noting that all of these rules can be automatically applied with _most_ editors, and I'm pretty sure you use PhpStorm, which they make it trivial (see the readme).

**Comment by david-fairbanks42** [comment]
Very good points. I've seen both cases.
Working on getting rules setup in my IDE.

**Comment by FatBoyXPC** [comment]
If you want to screenshare to set that up, let me know!

**Review by GlennKimbleJr — APPROVED** [review]
Looks good 👍 🚀

**Pull request merged**
