### PR TITLE
Change API routes to the plural version

### PR DESCRIPTION
**Pull request by david-fairbanks42**
Includes user, meeting and reservation.
Added a feature test for show meeting.

**WARNING: I've also changed Glenn's user route, make sure that's what you want.**

### CODE REVIEW

**Review by FatBoyXPC — APPROVED** [review]
Don't you just love when CI does its job?! Quick draw on that fix!

I just realized saw that the callback functions in the routes were getting modified. I forgot to add those to the linting rules. Think I should?

:shipit:

**Comment by david-fairbanks42** [comment]
I don't see why they shouldn't be under the same rules. The change seems minor from where we were at.

**Comment by david-fairbanks42** [comment]
As a note, the command lines to push failed, had to used pretty green button.

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "Run tests" is expected. At least 1 approving review is required by reviewers with write access.
To github.com:tampabaylaravel/meetup.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:tampabaylaravel/meetup.git'
```

**Comment by FatBoyXPC** [comment]
Ah, it's because `master` is now protected with at least 1 approved review and the CI to pass. I didn't realize if those were met you couldn't merge via CLI. Oh well, I'll take it for the protections we get.

**Pull request merged**
